"""empty message

Revision ID: 1007006c316c
Revises: 636efaf8c509
Create Date: 2024-09-14 11:22:23.914915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1007006c316c'
down_revision = '636efaf8c509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['applicant'], ['id'])
        batch_op.drop_column('job')

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_constraint('job_poster_fkey', type_='foreignkey')
        batch_op.drop_column('poster')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('job_poster_fkey', 'users', ['poster'], ['id'])

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
