"""empty message

Revision ID: 4a66e3f84c57
Revises: 81b5ce6b92d0
Create Date: 2024-09-14 11:30:07.784611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a66e3f84c57'
down_revision = '81b5ce6b92d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploader', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['uploader'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('uploader')

    # ### end Alembic commands ###
