"""empty message

Revision ID: 636efaf8c509
Revises: ea2baf6e1c6b
Create Date: 2024-09-14 11:21:15.275874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636efaf8c509'
down_revision = 'ea2baf6e1c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['poster'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
