"""empty message

Revision ID: 81b5ce6b92d0
Revises: 1007006c316c
Create Date: 2024-09-14 11:29:26.787606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81b5ce6b92d0'
down_revision = '1007006c316c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'job', ['listing'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('listing')

    # ### end Alembic commands ###
